### ISSUE TITLE
Cannot install php-firebase-cloud-messaging?

### ISSUE THREAD

**Issue by anta40** [sngrl/php-firebase-cloud-messaging#21]
This is my composer.json
```
{
        "require": {
                "snglr/php-firebase-cloud-messaging":"dev-master"
        }
}

```

When I ran **composer update**, I got:
>  Problem 1
>     - The requested package snglr/php-firebase-cloud-messaging could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by sngrl** [comment]
sng**RL**, not sng**LR**
