### ISSUE TITLE
How can I add custom cURL options?

### ISSUE THREAD

**Issue by worka** [sngrl/php-firebase-cloud-messaging#27]
Hi.

I need add **CURLOPT_SSL_VERIFYPEER** option

How can I do it in this code:

```
$client = new Client();
$client->setApiKey($server_key);
$client->injectGuzzleHttpClient(new \GuzzleHttp\Client());
```
I found this in the Guzzle documentation but I can not apply it
```
$client->request('GET', '/', [
    'curl' => [
        CURLOPT_INTERFACE => 'xxx.xxx.xxx.xxx'
    ]
]);
```
Thank you!!!

**Comment by Demonslay335** [comment]
You should be able to pre-config the Guzzle Client that is injected. It looks like you can set default options when initializing it.

Something like this perhaps.

```
$client->injectGuzzleHttpClient(new \GuzzleHttp\Client(['defaults' => [
    'verify' => false
]]));
```
https://stackoverflow.com/questions/28066409/how-to-ignore-invalid-ssl-certificate-errors-in-guzzle-5

**Comment by worka** [comment]
@Demonslay335, thanks

**Comment by Worka** [comment]
Done
