### ISSUE TITLE
Set message priority=high in readme

### ISSUE THREAD

**Issue by swaffoja** [sngrl/php-firebase-cloud-messaging#5]
I spent a fair amount of time trying to determine why my messages were not being delivered to my device. `$response->getStatusCode()` always returned status 200, but messages would not show up. I finally discovered that setting `$message->setPriority('high')` resolved my testing issues. I would suggest highlighting the priority setting within the sample code in README.md. I'm happy to submit a PR for the text change if you prefer.

**Comment by sngrl** [comment]
Status Code 200 is mean that FCM service successfully get your request and set him in the queue, it's not garantie that the message will be delivered.
Your pull request was merged, thank you.
