### ISSUE TITLE
try to send notification with sound but function setSound not found !!

### ISSUE THREAD

**Issue by waleedazam** [sngrl/php-firebase-cloud-messaging#8]
Hello 

I try to send notification with sound but function setSound not found i copy it from Notification class and set it in Message class but still not working 

any advice about how to use it or fixing it ?
Regards

**Comment by blumanski** [comment]
Try it this way

    $notification = new Notification('message title', 'message body');
    $notification->setTitle('Overwrite that title')
	->setSound(true)
	->setBody('overwrite the message body');

In context to

    $message
    ->setNotification(new Notification('title', 'body'))

Change to

    $message
    ->setNotification($notification)

**Comment by waleedazam** [comment]
thank you its work

**Comment by waleedazam** [comment]
I have new option in IOS notification its called content_available 
how to add it to notification to run it in background

**Comment by sngrl** [comment]
@waleedazam you can do it like this:

`$message->setJsonKey('content_available', true);`

**Comment by waleedazam** [comment]
great .. its work :+1:
